import assert from 'assert';

import { normalizePath } from './';

suite('utils', () => {
  suite('normalizePath', () => {
    test('forward-slash', () => {
      assert.deepStrictEqual(normalizePath(undefined), '');
      assert.deepStrictEqual(normalizePath(null), '');
      assert.deepStrictEqual(normalizePath(''), '');
      assert.deepStrictEqual(normalizePath('a'), 'a');
      assert.deepStrictEqual(normalizePath('a/'), 'a/');
      assert.deepStrictEqual(normalizePath('a/b'), 'a/b');
      assert.deepStrictEqual(normalizePath('a/b/'), 'a/b/');
      assert.deepStrictEqual(normalizePath('a/b/.'), 'a/b');
      assert.deepStrictEqual(normalizePath('a/b/./'), 'a/b/');
      assert.deepStrictEqual(normalizePath('a/b/./..'), 'a');
      assert.deepStrictEqual(normalizePath('a/b/./../'), 'a/');
      assert.deepStrictEqual(normalizePath('a/b/..'), 'a');
      assert.deepStrictEqual(normalizePath('a/b/../'), 'a/');
      assert.deepStrictEqual(normalizePath('a/b/../.'), 'a');
      assert.deepStrictEqual(normalizePath('a/b/.././'), 'a/');
      assert.deepStrictEqual(normalizePath('.'), './');
      assert.deepStrictEqual(normalizePath('./'), './');
      assert.deepStrictEqual(normalizePath('./a'), './a');
      assert.deepStrictEqual(normalizePath('./a/'), './a/');
      assert.deepStrictEqual(normalizePath('./a/b'), './a/b');
      assert.deepStrictEqual(normalizePath('./a/b/'), './a/b/');
      assert.deepStrictEqual(normalizePath('./a/b/.'), './a/b');
      assert.deepStrictEqual(normalizePath('./a/b/./'), './a/b/');
      assert.deepStrictEqual(normalizePath('./a/b/./..'), './a');
      assert.deepStrictEqual(normalizePath('./a/b/./../'), './a/');
      assert.deepStrictEqual(normalizePath('./a/b/..'), './a');
      assert.deepStrictEqual(normalizePath('./a/b/../'), './a/');
      assert.deepStrictEqual(normalizePath('./a/b/../.'), './a');
      assert.deepStrictEqual(normalizePath('./a/b/.././'), './a/');
      assert.deepStrictEqual(normalizePath('..'), '../');
      assert.deepStrictEqual(normalizePath('../'), '../');
      assert.deepStrictEqual(normalizePath('../a'), '../a');
      assert.deepStrictEqual(normalizePath('../a/'), '../a/');
      assert.deepStrictEqual(normalizePath('../a/b'), '../a/b');
      assert.deepStrictEqual(normalizePath('../a/b/'), '../a/b/');
      assert.deepStrictEqual(normalizePath('../a/b/.'), '../a/b');
      assert.deepStrictEqual(normalizePath('../a/b/./'), '../a/b/');
      assert.deepStrictEqual(normalizePath('../a/b/./..'), '../a');
      assert.deepStrictEqual(normalizePath('../a/b/./../'), '../a/');
      assert.deepStrictEqual(normalizePath('../a/b/..'), '../a');
      assert.deepStrictEqual(normalizePath('../a/b/../'), '../a/');
      assert.deepStrictEqual(normalizePath('../a/b/../.'), '../a');
      assert.deepStrictEqual(normalizePath('../a/b/.././'), '../a/');
      assert.deepStrictEqual(normalizePath('./.'), './');
      assert.deepStrictEqual(normalizePath('././'), './');
      assert.deepStrictEqual(normalizePath('./..'), '../');
      assert.deepStrictEqual(normalizePath('./../'), '../');
      assert.deepStrictEqual(normalizePath('../.'), '../');
      assert.deepStrictEqual(normalizePath('.././'), '../');
      assert.deepStrictEqual(normalizePath('../..'), '../../', '../..');
      assert.deepStrictEqual(normalizePath('../../'), '../../');
      assert.deepStrictEqual(normalizePath('a//b'), 'a/b');
      assert.deepStrictEqual(normalizePath('a//b//'), 'a/b/');
    });
    test('back-slash', () => {
      assert.deepStrictEqual(normalizePath('a'), 'a');
      assert.deepStrictEqual(normalizePath('a\\'), 'a/');
      assert.deepStrictEqual(normalizePath('a\\b'), 'a/b');
      assert.deepStrictEqual(normalizePath('a\\b\\'), 'a/b/');
      assert.deepStrictEqual(normalizePath('a\\b\\.'), 'a/b');
      assert.deepStrictEqual(normalizePath('a\\b\\.\\'), 'a/b/');
      assert.deepStrictEqual(normalizePath('a\\b\\.\\..'), 'a');
      assert.deepStrictEqual(normalizePath('a\\b\\.\\..\\'), 'a/');
      assert.deepStrictEqual(normalizePath('a\\b\\..'), 'a');
      assert.deepStrictEqual(normalizePath('a\\b\\..\\'), 'a/');
      assert.deepStrictEqual(normalizePath('a\\b\\..\\.'), 'a');
      assert.deepStrictEqual(normalizePath('a\\b\\..\\.\\'), 'a/');
      assert.deepStrictEqual(normalizePath('.'), './');
      assert.deepStrictEqual(normalizePath('.\\'), './');
      assert.deepStrictEqual(normalizePath('.\\a'), './a');
      assert.deepStrictEqual(normalizePath('.\\a\\'), './a/');
      assert.deepStrictEqual(normalizePath('.\\a\\b'), './a/b');
      assert.deepStrictEqual(normalizePath('.\\a\\b\\'), './a/b/');
      assert.deepStrictEqual(normalizePath('.\\a\\b\\.'), './a/b');
      assert.deepStrictEqual(normalizePath('.\\a\\b\\.\\'), './a/b/');
      assert.deepStrictEqual(normalizePath('.\\a\\b\\.\\..'), './a');
      assert.deepStrictEqual(normalizePath('.\\a\\b\\.\\..\\'), './a/');
      assert.deepStrictEqual(normalizePath('.\\a\\b\\..'), './a');
      assert.deepStrictEqual(normalizePath('.\\a\\b\\..\\'), './a/');
      assert.deepStrictEqual(normalizePath('.\\a\\b\\..\\.'), './a');
      assert.deepStrictEqual(normalizePath('.\\a\\b\\..\\.\\'), './a/');
      assert.deepStrictEqual(normalizePath('..'), '../');
      assert.deepStrictEqual(normalizePath('..\\'), '../');
      assert.deepStrictEqual(normalizePath('..\\a'), '../a');
      assert.deepStrictEqual(normalizePath('..\\a\\'), '../a/');
      assert.deepStrictEqual(normalizePath('..\\a\\b'), '../a/b');
      assert.deepStrictEqual(normalizePath('..\\a\\b\\'), '../a/b/');
      assert.deepStrictEqual(normalizePath('..\\a\\b\\.'), '../a/b');
      assert.deepStrictEqual(normalizePath('..\\a\\b\\.\\'), '../a/b/');
      assert.deepStrictEqual(normalizePath('..\\a\\b\\.\\..'), '../a');
      assert.deepStrictEqual(normalizePath('..\\a\\b\\.\\..\\'), '../a/');
      assert.deepStrictEqual(normalizePath('..\\a\\b\\..'), '../a');
      assert.deepStrictEqual(normalizePath('..\\a\\b\\..\\'), '../a/');
      assert.deepStrictEqual(normalizePath('..\\a\\b\\..\\.'), '../a');
      assert.deepStrictEqual(normalizePath('..\\a\\b\\..\\.\\'), '../a/');
      assert.deepStrictEqual(normalizePath('.\\.'), './');
      assert.deepStrictEqual(normalizePath('.\\.\\'), './');
      assert.deepStrictEqual(normalizePath('.\\..'), '../');
      assert.deepStrictEqual(normalizePath('.\\..\\'), '../');
      assert.deepStrictEqual(normalizePath('..\\.'), '../');
      assert.deepStrictEqual(normalizePath('..\\.\\'), '../');
      assert.deepStrictEqual(normalizePath('..\\..'), '../../', '../..');
      assert.deepStrictEqual(normalizePath('..\\..\\'), '../../');
      assert.deepStrictEqual(normalizePath('C:\\'), 'C:/');
      assert.deepStrictEqual(normalizePath('C:\\a'), 'C:/a');
      assert.deepStrictEqual(normalizePath('C:\\a\\'), 'C:/a/');
      assert.deepStrictEqual(normalizePath('a\\\\b'), 'a/b');
      assert.deepStrictEqual(normalizePath('a\\\\b\\\\'), 'a/b/');
    });
  });
});
